batch_size: 256
lr: 0.0003
num_epochs: 50
save_dir: "./training_logs"
use_early_stopping: True
patience: 10
min_delta: 0
save_n_epochs: 2
num_workers: 16
resnet: "34"
weight_decay: 0.0005
lr_scheduler_gamma: 0.9